### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Christelle-12** [bilalrajput09/Leaderboard-API-Project#3]
Hello @bilalrajput09 ,
Your project is complete! There is nothing else to say other than... it's time to merge it,
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉
![congzz](https://user-images.githubusercontent.com/105784335/232701169-b1d91be2-c4d5-4fbb-8578-e352d1fc4c1d.gif)
**Highlights**

- No Linter errors ✔️
- Good commit messages ✔️
- Well structured Markup ✔️

**Comment by harshi0102** [comment]
@bilalrajput09  You've done a fantastic job with no linter errors, good commit messages, and well-structured markup. Well done!

**Comment by bilalrajput09** [comment]
Thank you guys for reviewing my project. 😊
